.eslintrc.js, next.config.js, pages/api/hello.ts, pages/index.tsx
=> 🚨 fix compiler lint error

src/components/ResultBox.tsx, src/components/SearchBar.tsx, src/pages/index.tsx, src/types/Cocktail.ts
=> 💩  test api load

src/components/ResultBox.tsx
=> ✨  Load multiple API

src/components/AutoComplete.tsx, src/components/Item.tsx, src/components/ResultBox.tsx, src/components/SearchBar.tsx, src/components/TagList.tsx, src/pages/index.tsx
Refactor SearchBar, TagList. Add AutoComplete
=> Refactor SearchBar, TagList. Add AutoComplete

src/components/AutoComplete.tsx, src/components/Item.tsx, src/components/ResultBox.tsx, src/components/SearchBar.tsx, src/components/TagList.tsx, src/hooks/useData.ts, src/pages/detail.tsx, src/pages/index.tsx, src/utils/fetcher.ts
✨ Feat: Load API with multiple keys and remove dead codes
=> ✨ Feat: Load API with multiple keys and remove dead codes

src/components/AutoComplete.tsx, src/components/SearchContainer.tsx
=> ✨ Feat: 자동완성

src/components/SearchContainer.tsx, src/components/TagList.tsx
=> 🐛 Fix : Autocomplate click event

src/components/InfiniteScrollContainer.tsx, src/components/ResultCard.tsx, src/components/SearchContainer.tsx, src/pages/index.tsx
- scroll 값, tagList, 렌터링 아이템 개수
- 제출버튼 삭제 -> 자동제출
=> ✨ Feat: scroll 유지를 위해 세션스토리지 사용

src/components/AutoComplete.tsx
=> ♻️ Refactor: AutoComplete component

src/components/Category.tsx, src/components/ResultContainer.tsx, src/components/SearchContainer.tsx, src/components/TagList.tsx, src/pages/index.tsx, src/utils/utils.ts
- 중복코드 정리 및 함수 처리
- util함수 추가
- 빈 fragment -> null로 변경
=> ♻️ Refactor: SearchContainer, add utils.ts

src/components/SearchContainer.tsx
=> ✨ feat: Add input reset button

src/pages/detail.tsx
=> ✨ feat: Add goback button

src/components/FavoritesCard.tsx, src/components/ResultCard.tsx, src/components/ResultContainer.tsx, src/pages/favorites.tsx, src/styles/ResponsiveGrid.tsx
- favorites page 반응형 grid 구현
- ResultContainer 반응형 grid로 변경
=> 💄 Update: ResponsiveGrid style

src/components/FavoritesCard.tsx, src/components/ResultCard.tsx, src/utils/utils.ts
=> ✨ feat: Add Like/Unlike button for favorites

src/components/Category.tsx, src/components/Error.tsx, src/components/FavoritesCard.tsx, src/components/Loading.tsx, src/components/ResultCard.tsx, src/components/ResultContainer.tsx, src/components/SearchContainer.tsx, src/components/TagList.tsx, src/pages/detail.tsx, src/pages/favorites.tsx, src/pages/index.tsx
- 데이터 로딩, 에러 컴포넌트가 추가되었습니다.
- 처음 입력에 대해 자동완성을 보여주지 않는 에러를 해결했습니다.
```
const [isNewInput, setIsNewInput] = useState<boolean>(true);
```
- 일부 UI가 (약간) 개선되었습니다.
=> 💄 Feature/UI

src/components/AutoComplete.tsx, src/components/Category.tsx, src/components/SearchContainer.tsx, src/components/TagList.tsx
- 타입 any로 지정된 이벤트 인자들에 대해 타입을 지정했습니다.
=> ♻️ refactor: Assign specific type to event arguments

src/components/SearchContainer.tsx, src/styles/globals.css
- input value가 있을 때만 입력취소 버튼을 활성화합니다.
=> ✨ feat: Show reset input button after typing

src/components/Category.tsx, src/components/ResultCard.tsx, src/components/SearchContainer.tsx
- 첫글자 대문자, 뒤에는 소문자가 오도록 통일된 데이터로 수정
=> 🐛 Fix: Set every ingredient's format consistence

src/components/ResultCard.tsx, src/components/layouts/Header.tsx, src/components/layouts/Layout.tsx, src/pages/_app.tsx, src/pages/index.tsx
- 공통 Layout 적용
- 이미지 로드중 배경 지정
=> 💄 Feat: Set common layout & add image background

src/components/SearchContainer.tsx, src/components/TagList.tsx
- not a function issue
- add event type
=> 🐛 Fix : Resolve first rendering issue
